# Generated by Django 5.2.17 on 2026-08-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_time', '-priority']},
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='is_achived',
            new_name='is_archived',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='is_achived',
            new_name='is_archived',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='priorty',
            new_name='priority',
        ),
    ]
