# Generated by Django 5.2.16 on 2026-08-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0003_dailyentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DailyEntry',
        ),
    ]
